{
  "os": "linux",
  "jdk": "oraclejdk8",
  "dist": "trusty",
  "group": "stable",
  "script": [
    "./gradlew clean",
    "./gradlew assembleDebug"
  ],
  "android": {
    "licenses": [
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'
    ],
    "components": [
      "tools",
      "platform-tools",
      "build-tools-27.0.1",
      "extra-android-m2repository",
      "extra-google-android-support",
      "android-27"
    ]
  },
  "language": "android",
  "before_install": [
    "yes | sdkmanager \"platforms;android-27\""
  ]
}
